### ISSUE TITLE
Error "Could not determine  a title id for this" when export and run the project

### ISSUE THREAD

**Issue by natnankumchin** [Structed/godot-playfab#117]
After exporting and run the project, when using Login with Custom ID. it shows the error "Could not determine  a title id for this"
But running the project in Editor, the login fuction works fine.

godot-playfab version: 1.0.0
Godot 4.1 beta1

**Comment by Structed** [comment]
This was a regression. Fixes a problem where, for Godot 3, I had naively skipped the first three elements of an object that was to be serialized, because it only contained Godot specific metadata that wouldn't need serialization in the context of serialising to JSON for HTTP requests.

Godot 3 always had these in the same order, at the first three elements of an object.

However, with Godot 4, this order is no longer guaranteed. I had fixed this at one point, but some of that seems to have gotten lost in the migration effort.

Thank you very much for finding this, @natnankumchin!
