### ISSUE TITLE
How do players receive signal events?

### ISSUE THREAD

**Issue by shafnaz** [Structed/godot-playfab#124]
i have a board game with 4 players. as 1 player makes a move, i send the data to playfab, either playstream or telemetry, and it's done successfully. How do other players listen to these events to update their side of the game? what's the signal for getting that data? But i also have to make sure I'm sending the data to those specific players, and not others.
Thank you.

**Comment by Structed** [comment]
Hi this is not something godot-playfab is great at. Since godot-playfab only covers the PlayFab Services API (the [REST API](https://learn.microsoft.com/en-us/gaming/playfab/api-references/?view=playfab-rest)), you cannot do real-time notifications.

This is where [PlayFab Lobby](https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/lobby/) with its PubSub system would shine, or [PlayFab Party](https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/), so you can put everyone in a peer-to-peer network and share data.
The "problem" Here is, that godot-playfab does not integrate those features yet. You may only use this by integrating the native C++ SDKs.

If you really want to do it with godot-playfab, you can do it this way (but with polling instead of notifications):

- Player 1 stores data in a group entity
- Player 1 goes to polling mode (as Player 2 is already)
- Player 2 polls the API every few seconds to check whether the group entity was written to
- If new data is available, Player 2 can do their turn
- Player 2 writes new data

And so forth.

**Comment by Structed** [comment]
This should have been a discussion. If you're want to consider discussing this further, please use discussions or the discord.

Thank you!

**Comment by shafnaz** [comment]
i see. Thank you. Great job with the plugin, looking forward to new things with this addon!
