### ISSUE TITLE
Update Project Logo

### ISSUE THREAD

**Issue by Structed** [Structed/godot-playfab#9]
* Create a crisper, larger version of the current logo:
  * [Logo Image](https://github.com/Structed/godot-playfab/blob/6aeda37877684b1a070ff2cf279c64c270ba17ad/raw_assets/logo.png)
  * [Paint.NET Project file](https://github.com/Structed/godot-playfab/blob/6aeda37877684b1a070ff2cf279c64c270ba17ad/raw_assets/logo.pdn)
* Create a scaled down for icon purposes

**Comment by lentsius-bark** [comment]
I've started working on vectorizing the logo and also went ahead trying a slight variation of the current design

I believe the version which has a gap instead of full on merging of both icons better communicates its shape also when smaller, because the lines in the merged version do not line up, creating a confusing visual hierarchy and non-flowing lines.

![image](https://user-images.githubusercontent.com/38346332/156878356-25d1ae56-4b1f-449e-95a7-1204ad6d969d.png)
![image](https://user-images.githubusercontent.com/38346332/156878362-eb0c1559-f356-4270-aa85-c08354aca77e.png)

**Comment by Structed** [comment]
Oh I love the version with the gap, this indeed makes the shapes clearer and it just "looks better", to my eye.

Also, it kind of gets close to my idea of the PlayFab inner hexagon part seeming like the "terminator eye" of the Godot bot.

Perhaps if you could show how it would look like if that would be repositioned in a way that it actually looks like the eye? Do you think that would work?

Otherwise I am already sooooo happy about what you came up with. Thank you do much!♥️

**Comment by lentsius-bark** [comment]
@Structed although i think it'll be too small, I'll give it a go, experimentation is always a plus, I'll send the mock up in a bit.

**Comment by lentsius-bark** [comment]
did you mean something along these lines or even more of an eye? @Structed 
![image](https://user-images.githubusercontent.com/38346332/156966207-c0bbb068-b0c6-474c-a0bf-ec771faedac9.png)

**Comment by Structed** [comment]
Even more of an eye, but I just tried it, and it looks really wonky 😁

I guess your original version with the gap is the best. Want to make a PR?

**Comment by lentsius-bark** [comment]
made a pr #19

**Comment by Structed** [comment]
Merged. Thanks, @lentsius-bark!
